extends BaseTest

## Golden fixtures: 50 static Draw-1 cases comparing the decoder + builder
## output against independently-generated expectations persisted in
## data/legacy/golden/golden_draw1.json. Expectations are never generated by
## the runtime decoder during the test run.

const GOLDEN_PATH := "res://data/legacy/golden/golden_draw1.json"
const FIXTURE_COUNT := 50

func test_golden_file_has_expected_shape() -> void:
	var f := FileAccess.open(GOLDEN_PATH, FileAccess.READ)
	check_true(f != null, "golden file exists")
	if f == null:
		return
	var json_text := f.get_as_text()
	f.close()
	var parsed: Variant = JSON.parse_string(json_text)
	check_true(parsed != null, "golden json parses")
	if parsed == null:
		return
	var fixtures: Array = parsed
	check_eq(fixtures.size(), FIXTURE_COUNT, "fixture count")
	for fix in fixtures:
		check_eq((fix as Dictionary)["encoded"].length(), 52, "encoded length")

func test_golden_fixtures_match_decoder_and_builder() -> void:
	var fixtures := _load_fixtures()
	for fix in fixtures:
		var index: int = fix["index"]
		var encoded: String = fix["encoded"]
		var expected_tableau: Array = fix["tableau"]
		var expected_stock: Array = fix["stock"]
		var ids := LegacyDealDecoder.decode(encoded)
		check_eq(ids.size(), 52, "fixture %d decode size" % index)
		if ids.size() != 52:
			continue
		var built := LegacyDealBuilder.build(ids)
		var tableau: Array = built["tableau"]
		var stock: Array[CardData] = built["stock"]
		# 52/52 coverage: every card accounted for, no duplicates
		var seen := {}
		var total := 0
		for c in 7:
			var col_cards: Array[CardData] = tableau[c]
			check_eq(col_cards.size(), c + 1, "fixture %d col %d size" % [index, c])
			for j in col_cards.size():
				total += 1
				var card := col_cards[j]
				var exp: Dictionary = expected_tableau[c][j]
				check_eq(card.id, exp["id"], "fixture %d col %d card %d id" % [index, c, j])
				check_eq(card.face_up, exp["face_up"], "fixture %d col %d card %d face_up" % [index, c, j])
				if seen.has(card.id):
					check(false, "fixture %d duplicate id %d" % [index, card.id])
				seen[card.id] = true
		check_eq(stock.size(), 24, "fixture %d stock size" % index)
		for j in stock.size():
			total += 1
			check_eq(stock[j].id, expected_stock[j], "fixture %d stock %d id" % [index, j])
			check_false(stock[j].face_up, "fixture %d stock %d face-down" % [index, j])
			if seen.has(stock[j].id):
				check(false, "fixture %d duplicate stock id %d" % [index, stock[j].id])
			seen[stock[j].id] = true
		check_eq(total, 52, "fixture %d total 52" % index)
		check_eq(seen.size(), 52, "fixture %d unique 52" % index)

func test_golden_first_fixture_spot_check() -> void:
	# Manually derived from the first record's reversed bytes (ADR-004):
	# record ends "...92;3" so R[0] = '3'-'0' = 3, R[1] = ';'-'0' = 11, R[2] = '2'-'0' = 2.
	var fixtures := _load_fixtures()
	var fix: Dictionary = fixtures[0]
	var ids := LegacyDealDecoder.decode(fix["encoded"])
	check_eq(ids[0], 3, "R0")
	check_eq(ids[1], 11, "R1")
	check_eq(ids[2], 2, "R2")
	var built := LegacyDealBuilder.build(ids)
	var col0: Array[CardData] = built["tableau"][0]
	check_eq(col0[0].id, 3, "col0 card is first draw-order id")
	check_true(col0[0].face_up, "col0 card face-up")

func _load_fixtures() -> Array:
	var f := FileAccess.open(GOLDEN_PATH, FileAccess.READ)
	if f == null:
		return []
	var json_text := f.get_as_text()
	f.close()
	var parsed: Variant = JSON.parse_string(json_text)
	if parsed == null:
		return []
	return parsed
